const mongoose = require('mongoose');
const Node = require('./Node');

const ConnectionSchema = new mongoose.Schema({
  // _id is automatically generated by Mongoose
  startNode: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Node', // Reference to the start Node
    required: true,
  },
  endNode: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Node', // Reference to the end Node
    required: true,
  },
  // Add other connection properties if needed
});

const Connection = mongoose.model('Connection', ConnectionSchema);

module.exports = Connection;
