const mongoose = require('mongoose');

const FileSchema = new mongoose.Schema({
  // _id is automatically generated by Mongoose
  id: { // Store temporary frontend ID if needed for initial saving response
     type: String,
     required: false,
  },
  name: {
    type: String,
    required: true,
  },
  path: {
    type: String,
    required: false, // Path is optional for new files before saving
  },
});

const File = mongoose.model('File', FileSchema);

module.exports = File;
