const mongoose = require('mongoose');
const Node = require('./Node');
const Connection = require('./Connection');

const MapSchema = new mongoose.Schema({
  // _id is automatically generated by Mongoose
  name: {
    type: String,
    required: true,
  },
  nodes: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Node', // Reference to the Node model
    },
  ],
  connections: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Connection', // Reference to the Connection model
    },
  ],
  // Add other map-specific properties if needed
});

const Map = mongoose.model('Map', MapSchema);

module.exports = Map;
