const mongoose = require('mongoose');
const File = require('./File');

const NodeSchema = new mongoose.Schema({
  // _id is automatically generated by Mongoose
  id: { // Store temporary frontend ID
     type: String,
     required: true,
  },
  position: {
    x: { type: Number, required: true },
    y: { type: Number, required: true },
  },
  title: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    default: '',
  },
  links: { // Assuming links are stored as strings
    type: [String],
    default: [],
  },
  files: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'File', // Reference to the File model
    },
  ],
  isDone: {
    type: Boolean,
    default: false,
  },
});

const Node = mongoose.model('Node', NodeSchema);

module.exports = Node;
